name: Build on Windows
on: push
jobs:
  build:
    runs-on: windows-2019
    steps:
      -  run: |
          choco install wget -y
          cd C:\
          wget "https://githubpaveltest.s3.eu-central-1.amazonaws.com/ibsetup_v10_2636_console.exe" -O "C:\ibsetup_v10_2636_console.exe"
          ./ibsetup_v10_2636_console.exe /Install /Components=Agent /Coordinator=3.67.194.114 /Agent:AgentRole=Initiator /Agent:InitiatorType=Floating /Agent:OpenFirewall=ON /AddToPath=ON /Agent:InstallAddins=OFF
          New-Item -Path 'HKLM:\SOFTWARE\WOW6432Node\Xoreax\IncrediBuild\Log'
          New-ItemProperty -Path 'HKLM:\SOFTWARE\WOW6432Node\Xoreax\IncrediBuild\Log' -Name 'Level' -Value "4" -PropertyType String -Force
     
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
              
      - name: Clone Repository and Rebuild with Incredibuild
        run: |
            cd C:\
            git clone https://github.com/PavelGo3110/TestBAC-100-.git
            cd C:\TestBAC-100-
            $env:Path = 'C:\Windows\System32'
            $env:Path = 'C:\Program Files (x86)\IncrediBuild'
            BuildConsole.exe 'C:\TestBAC-100-\TestBAC(100).sln' /rebuild /cfg="Debug|x64" /usemsbuild
                                             
      - name: Upload artifacts    
        uses: actions/upload-artifact@v2
        with:
           name: my-artifact
           path: |
             C:\Program Files (x86)\IncrediBuild\History
             C:\Program Files (x86)\IncrediBuild\Logs
